discord:
  channel: general
  token: 'NTg3OTI0NTUzNDM1NzA5NDQx.XRywRg.N6Y7M-50ax7XnqGE0J4GCkthw2E'
jokes:
  - What do you call a hippie's wife? A Mississippi!
  - What did the duck say when she bought a lipstick? Put it on my bill!
  - I hate Russian dolls. They're so full of themselves.
  - What do you call a man with a rubber toe? Roberto!
  - Where did the computer go dancing? The disc-o!
  - What do bees do if they need a ride? Wait at the buzz stop!
  - What do you give to a sick lemon? Lemon aid!
  - What did the little mountain say to the bigger mountain? Hi Cliff!
  - What do you call a monkey that loves Doritos? A chipmunk!
  - Why did the can crusher quit his job? Because it was soda pressing!
  - Why are there gates around cemeteries? Because people are dying to get in!
  - What do you call a cow with two legs? Lean beef!
  - I just went to an emotional wedding. Even the cake was in tiers.
  - What do you call a dangerous sun shower? A rain of terror!
  - Why do seagulls fly over the sea? Because if they flew over the bay, they've bagels!
  - What do you call a farm that makes bad jokes? Corny!
  - Why do fish live in salt water? Because pepper makes them sneeze!
  - What streets to ghosts haunt? Dead ends!
  - What did Winnie the Pooh say to his agent? "Show me the honey!"
  - I got fired from my job at the bank today. An old lady came in and asked me to check her balance, so I pushed her over.
  - What did the janitor say when he jumped out of the closet? "Supplies!"
  - I have an addiction to cheddar cheese. But it's only mild.
  - What did the buffalo say when his son left? Bison!
  - My grandfather has the heart of a lion and a lifetime ban from the National Zoo.
  - Did you hear about the two thieves who stole a calendar? They each got six months.
  - Three fish are in a tank. One asks the others, "How do you drive this thing?"





